puts "The students of Villains Academy"
puts "---------------"
puts "Dr. Hannibal Lecter"
puts "Darth Vader"
puts "Nurse Ratched"
puts "michael Corleone"
puts "Alex Delarge"
puts "The Wicked Witch of the West"
puts "Terminator"
puts "Freddy Krueger"
puts "The Joker"
puts "Joffrey Baratheon"
puts "Norman Bates"
# Print total number of students
print "Overall, we have"
print 11
puts " great students"
